language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.1.1
    - android-26
script:
  - ./gradlew uploadArchives
after_success:
  - .travis_push.sh
